apiVersion: apps/v1
kind: Deployment
metadata:
  name: devartisan-frontend
  labels:
    app: devartisan-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devartisan-frontend
  template:
    metadata:
      labels:
        app: devartisan-frontend
    spec:
      containers:
      - name: devartisan-frontend
        image: ${{ secrets.DOCKER_USERNAME }}/devartisan-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devartisan-frontend
spec:
  selector:
    app: devartisan-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer