name: DevArtisan CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run backend tests
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
        run: |
          cd backend
          source venv/bin/activate
          pytest

      - name: Security Tests
        run: |
          cd backend
          source venv/bin/activate
 ▋