name: DevArtisan Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t devartisan-backend:latest ./backend
          docker tag devartisan-backend:latest ${{ secrets.DOCKER_USERNAME }}/devartisan-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devartisan-backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t devartisan ▋